name: Sync Upstream

on:
  schedule:
    # 매 30분마다 확인 (필요시 조정)
    - cron: '*/30 * * * *'
  workflow_dispatch: # 수동 실행도 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Sync upstream
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: main
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: gyb0719/naver-maps-field-management-customer
        
    - name: Check for new commits
      run: echo "New commits available - ${{ steps.sync.outputs.has_new_commits }}"